services:
  invoice:
    build:
      context: .
      dockerfile: ./apps/invoice/Dockerfile
      target: development
    command: pnpm run start:dev invoice
    env_file:
      - ./apps/invoice/.env
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: pnpm run start:dev auth
    env_file:
      - ./apps/auth/.env
    ports:
      - "3001:3001"
    volumes:
      - .:/usr/src/app

  mongo:
    image: mongo
