services:
  invoice:
    build:
      context: .
      dockerfile: ./apps/invoice/Dockerfile
      target: development
    command: pnpm run start:debug invoice
    env_file:
      - ./apps/invoice/.env
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - .:/usr/src/app

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: pnpm run start:debug auth
    env_file:
      - ./apps/auth/.env
    ports:
      - "3001:3001"
      - "8229:9229"
    volumes:
      - .:/usr/src/app

  payments:
    build:
      context: .
      dockerfile: ./apps/payments/Dockerfile
      target: development
    command: pnpm run start:debug payments
    env_file:
      - ./apps/payments/.env
    ports:
      - "7229:9229"
    volumes:
      - .:/usr/src/app

  notifications:
    build:
      context: .
      dockerfile: ./apps/notifications/Dockerfile
      target: development
    command: pnpm run start:debug notifications
    env_file:
      - ./apps/notifications/.env
    ports:
      - "6229:9229"
    volumes:
      - .:/usr/src/app

  cron:
    build:
      context: .
      dockerfile: ./apps/cron/Dockerfile
      target: development
    command: pnpm run start:debug cron
    env_file:
      - ./apps/cron/.env
    ports:
      - "5229:9229"
    volumes:
      - .:/usr/src/app

  mongo:
    image: mongo
    restart: always
    ports:
      - '27037:27017'
    volumes:
      - mongo-development-data:/data/db

  rabbitmq:
    image: rabbitmq
    ports:
      - '3672:5672'

volumes:
  mongo-development-data: